SHELL:cmd.exe
1:
	cls
2:
	del .\fake_data\MNIST\raw\train-labels-idx1-ubyte
	del .\fake_data\MNIST\raw\train-images-idx3-ubyte
	del .\fake_data\MNIST\raw\t10k-labels-idx1-ubyte
	del .\fake_data\MNIST\raw\t10k-images-idx3-ubyte
main:
	del .\fake_data\MNIST\raw\train-labels-idx1-ubyte
	del .\fake_data\MNIST\raw\train-images-idx3-ubyte
	del .\fake_data\MNIST\raw\t10k-labels-idx1-ubyte
	del .\fake_data\MNIST\raw\t10k-images-idx3-ubyte
	cls
	python main.py
	del .\fake_data\MNIST\raw\train-labels-idx1-ubyte
	del .\fake_data\MNIST\raw\train-images-idx3-ubyte
	del .\fake_data\MNIST\raw\t10k-labels-idx1-ubyte
	del .\fake_data\MNIST\raw\t10k-images-idx3-ubyte
vote:
	del .\fake_data\MNIST\raw\train-labels-idx1-ubyte
	del .\fake_data\MNIST\raw\train-images-idx3-ubyte
	del .\fake_data\MNIST\raw\t10k-labels-idx1-ubyte
	del .\fake_data\MNIST\raw\t10k-images-idx3-ubyte
	cls
	python vote_system.py
	del .\fake_data\MNIST\raw\train-labels-idx1-ubyte
	del .\fake_data\MNIST\raw\train-images-idx3-ubyte
	del .\fake_data\MNIST\raw\t10k-labels-idx1-ubyte
	del .\fake_data\MNIST\raw\t10k-images-idx3-ubyte