SHELL:cmd.exe
0:
	cls
	python main.py
1:
	cls
2:
	del .\fake_data\MNIST\raw\train-labels-idx1-ubyte
	del .\fake_data\MNIST\raw\train-images-idx3-ubyte
	del .\fake_data\MNIST\raw\t10k-labels-idx1-ubyte
	del .\fake_data\MNIST\raw\t10k-images-idx3-ubyte
